// The reward collection: a themed set of real photo cards (gems & minerals,
// animals, space) with a rarity and a true fact to learn, for the
// kid. Photos live in public/collection/<id>.jpg, fetched by
// scripts/fetch-collection.mjs from scripts/collection-sources.json; credits
// for each photo are generated into src/content/collectionCredits.ts. The
// box/album UI is built on top of this file by another builder - COLLECTION,
// findItem, itemsInSet, itemImageUrl and RARITY_META are the contract.

import type { Rarity } from '../store/progress'

export type CollectionSet = 'gems' | 'animals' | 'space'

export interface CollectionItem {
  id: string
  set: CollectionSet
  name: string
  rarity: Rarity
  emoji: string
  fact: string
  where: string
  say?: string
}

export const SETS: { id: CollectionSet; name: string; emoji: string }[] = [
  { id: 'gems', name: 'Gems & minerals', emoji: '💎' },
  { id: 'animals', name: 'Animals', emoji: '🦊' },
  { id: 'space', name: 'Space', emoji: '🪐' },
]

function item(
  id: string,
  set: CollectionSet,
  name: string,
  rarity: Rarity,
  emoji: string,
  fact: string,
  where: string,
  say?: string,
): CollectionItem {
  return say ? { id, set, name, rarity, emoji, fact, where, say } : { id, set, name, rarity, emoji, fact, where }
}

export const COLLECTION: CollectionItem[] = [
  // --- Gems & minerals (24) ---------------------------------------------
  item(
    'quartz',
    'gems',
    'Quartz',
    'common',
    '🪨',
    'Quartz is one of the most common minerals on Earth. It often grows in six-sided crystal points that sparkle in sunlight.',
    'Found in: almost everywhere on Earth',
  ),
  item(
    'rose-quartz',
    'gems',
    'Rose quartz',
    'common',
    '💗',
    'Rose quartz gets its soft pink colour from tiny mineral traces inside it. People often carve it into hearts and smooth palm stones.',
    'Found in: Brazil and Madagascar',
  ),
  item(
    'amethyst',
    'gems',
    'Amethyst',
    'common',
    '💜',
    'Amethyst is purple quartz coloured by traces of iron. Long ago, people thought it could keep them safe on adventures.',
    'Found in: Brazil and Uruguay',
    'Say: am-uh-thist',
  ),
  item(
    'citrine',
    'gems',
    'Citrine',
    'common',
    '🟡',
    "Citrine is a sunny yellow quartz named after the citron fruit. Most citrine sold today started out as purple amethyst, heated until it turned gold.",
    'Found in: Brazil and Zambia',
  ),
  item(
    'agate',
    'gems',
    'Agate',
    'common',
    '🪨',
    'Agate forms in rings of colour, like a rainbow frozen in stone. Every agate has its own pattern, so no two are exactly alike.',
    'Found in: Brazil and Mexico',
  ),
  item(
    'jasper',
    'gems',
    'Jasper',
    'common',
    '🪨',
    'Jasper is a colourful stone that people have carved into beads and seals for thousands of years. Its swirling patterns can look like tiny landscapes.',
    'Found in: India and Madagascar',
  ),
  item(
    'obsidian',
    'gems',
    'Obsidian',
    'common',
    '⚫',
    'Obsidian is volcanic glass, made when hot lava cools very fast. It can be so smooth and sharp that ancient people shaped it into tools.',
    'Found in: volcanoes around the world',
  ),
  item(
    'pyrite',
    'gems',
    'Pyrite',
    'common',
    '🟨',
    "Pyrite is nicknamed fool's gold because it glitters just like real gold. It often forms in perfect little cube shapes.",
    'Found in: Spain and Peru',
  ),
  item(
    'malachite',
    'gems',
    'Malachite',
    'common',
    '🟢',
    'Malachite is a bright green stone with swirly bands, like tree rings. Ancient Egyptians ground it up to make green eye paint.',
    'Found in: the Democratic Republic of the Congo',
  ),
  item(
    'turquoise',
    'gems',
    'Turquoise',
    'common',
    '🩵',
    'Turquoise gets its blue-green colour from copper in the rock around it. People have carved it into jewellery for thousands of years.',
    'Found in: Iran and the south-western USA',
  ),
  item(
    'lapis-lazuli',
    'gems',
    'Lapis lazuli',
    'uncommon',
    '🔵',
    'Lapis lazuli is a deep blue rock speckled with gold flecks of pyrite. Painters once crushed it to make a brilliant blue paint.',
    'Found in: Afghanistan',
    'Say: LAP-iss LAZ-yoo-lee',
  ),
  item(
    'garnet',
    'gems',
    'Garnet',
    'uncommon',
    '🔴',
    'Garnet comes in almost every colour, though deep red is the most common. Its name comes from a word for pomegranate seeds, which it resembles.',
    'Found in: India and East Africa',
  ),
  item(
    'topaz',
    'gems',
    'Topaz',
    'uncommon',
    '🟠',
    'Topaz can be blue, pink, or golden yellow, and it is one of the harder gems around. It is the birthstone for November.',
    'Found in: Brazil and Sri Lanka',
  ),
  item(
    'aquamarine',
    'gems',
    'Aquamarine',
    'uncommon',
    '🩵',
    'Aquamarine means seawater in Latin, and its pale blue colour matches the name perfectly. Sailors once carried it as a good-luck charm at sea.',
    'Found in: Brazil and Pakistan',
  ),
  item(
    'peridot',
    'gems',
    'Peridot',
    'uncommon',
    '🟢',
    'Peridot is a lively green gem that forms deep underground, inside volcanic rock. Tiny bits of it have even been found inside meteorites from space.',
    'Found in: Arizona, USA and Myanmar',
  ),
  item(
    'tourmaline',
    'gems',
    'Tourmaline',
    'uncommon',
    '🌈',
    'Tourmaline comes in more colours than almost any other gem, sometimes several colours in one crystal. Some crystals are pink on one end and green on the other.',
    'Found in: Brazil and Nigeria',
    'Say: TOOR-ma-leen',
  ),
  item(
    'opal',
    'gems',
    'Opal',
    'uncommon',
    '⚪',
    'Opal can flash every colour of the rainbow when it catches the light. This sparkle happens because of tiny spheres of silica packed inside it.',
    'Found in: Australia',
  ),
  item(
    'emerald',
    'gems',
    'Emerald',
    'rare',
    '💚',
    'Emerald is a rich green gem, coloured by traces of chromium. It is often found with tiny natural marks inside, nicknamed its garden.',
    'Found in: Colombia and Zambia',
  ),
  item(
    'ruby',
    'gems',
    'Ruby',
    'rare',
    '❤️',
    'Ruby is a deep red gem, and its colour comes from a trace of chromium. It is one of the toughest gems, second only to diamond.',
    'Found in: Myanmar and Thailand',
  ),
  item(
    'sapphire',
    'gems',
    'Sapphire',
    'rare',
    '💙',
    'Sapphire is famous for its deep blue colour, but it can also be pink, yellow, or even colourless. It is the very same mineral as ruby, just a different colour.',
    'Found in: Sri Lanka and Australia',
  ),
  item(
    'gold-nugget',
    'gems',
    'Gold nugget',
    'rare',
    '🪙',
    'A gold nugget is a lump of pure gold found in rivers or rock, with no melting or shaping needed. Gold never rusts, so nuggets can shine for thousands of years.',
    'Found in: riverbeds and mines worldwide',
  ),
  item(
    'tanzanite',
    'gems',
    'Tanzanite',
    'epic',
    '🔵',
    'Tanzanite is a blue-purple gem found in only one place on Earth, near Mount Kilimanjaro. It was only discovered in 1967.',
    'Found in: Tanzania, only near Mount Kilimanjaro',
    'Say: tan-zuh-NITE',
  ),
  item(
    'alexandrite',
    'gems',
    'Alexandrite',
    'epic',
    '💚',
    'Alexandrite is a magic-trick gem: it looks green in daylight and red under warm indoor light. It was named after a Russian tsar.',
    'Found in: Russia and Sri Lanka',
    'Say: al-ex-AN-drite',
  ),
  item(
    'diamond',
    'gems',
    'Diamond',
    'legendary',
    '💎',
    'Diamond is the hardest natural material on Earth, formed under huge heat and pressure deep underground. Its name comes from a Greek word meaning unbreakable.',
    'Found in: South Africa and Russia',
  ),

  // --- Animals (36) -------------------------------------------------------
  item(
    'fox',
    'animals',
    'Fox',
    'common',
    '🦊',
    'Foxes have such good hearing that they can hear small rodents moving underground before they dig. They wrap their long bushy tail around themselves like a blanket to keep warm.',
    'Lives in: forests and fields worldwide',
  ),
  item(
    'frog',
    'animals',
    'Frog',
    'common',
    '🐸',
    'Frogs breathe partly through their skin, which is why they need to stay damp. Baby frogs, called tadpoles, live underwater and breathe with gills.',
    'Lives in: ponds and wet forests',
  ),
  item(
    'hedgehog',
    'animals',
    'Hedgehog',
    'common',
    '🦔',
    'A hedgehog has about 5,000 spines, though they are soft at birth and harden within days. When scared, it curls into a tight, prickly ball.',
    'Lives in: gardens and hedgerows in Europe',
  ),
  item(
    'rabbit',
    'animals',
    'Rabbit',
    'common',
    '🐰',
    'Rabbits can see almost all the way around themselves without turning their head. Their strong back legs let them leap many times their own body length.',
    'Lives in: meadows and burrows worldwide',
  ),
  item(
    'duck',
    'animals',
    'Duck',
    'common',
    '🦆',
    "A duck's feathers are naturally waterproof, coated in oil from a gland near its tail. Ducklings can swim within hours of hatching.",
    'Lives in: ponds, rivers and lakes',
  ),
  item(
    'squirrel',
    'animals',
    'Squirrel',
    'common',
    '🐿️',
    'Squirrels bury nuts all over their territory and remember most hiding spots by smell. They help forests grow by planting seeds they forget.',
    'Lives in: trees in forests and parks',
  ),
  item(
    'deer',
    'animals',
    'Deer',
    'common',
    '🦌',
    'Deer can turn their ears separately to listen for danger from two directions at once. Male deer grow a brand new set of antlers every year.',
    'Lives in: woodlands and grasslands',
  ),
  item(
    'owl',
    'animals',
    'Owl',
    'common',
    '🦉',
    'Owls can turn their heads about 270 degrees because they have extra neck bones. Their soft feathers let them fly and hunt almost silently.',
    'Lives in: forests and barns at night',
  ),
  item(
    'honeybee',
    'animals',
    'Honeybee',
    'common',
    '🐝',
    'A honeybee visits dozens of flowers on a single trip to gather nectar and pollen. Bees dance in special patterns to tell each other where the best flowers are.',
    'Lives in: hives in fields and gardens',
  ),
  item(
    'ladybird',
    'animals',
    'Ladybird',
    'common',
    '🐞',
    "A ladybird's bright colours warn birds that it does not taste very nice. Each species has its own spot pattern, a bit like a uniform.",
    'Lives in: gardens and meadows',
  ),
  item(
    'sea-turtle',
    'animals',
    'Sea turtle',
    'common',
    '🐢',
    'Sea turtles can hold their breath for hours by slowing their heartbeat right down. Females often return to the very beach where they hatched to lay their own eggs.',
    'Lives in: warm oceans worldwide',
  ),
  item(
    'dolphin',
    'animals',
    'Dolphin',
    'common',
    '🐬',
    'Dolphins sleep with one half of their brain awake at a time, so they can keep breathing. They use clicks and whistles to find fish and talk to each other.',
    'Lives in: oceans and some rivers',
  ),
  item(
    'penguin',
    'animals',
    'Penguin',
    'common',
    '🐧',
    "Penguins can't fly, but they are brilliant swimmers, some reaching 35 km per hour underwater. Thick feathers and a layer of fat keep them warm in icy water.",
    'Lives in: Antarctica and southern coasts',
  ),
  item(
    'koala',
    'animals',
    'Koala',
    'uncommon',
    '🐨',
    'Koalas sleep up to 20 hours a day because eucalyptus leaves give them very little energy. Their fingerprints look so much like human ones that experts have to check them closely.',
    'Lives in: eucalyptus trees in Australia',
  ),
  item(
    'flamingo',
    'animals',
    'Flamingo',
    'uncommon',
    '🦩',
    'Flamingos are actually born grey, and turn pink from pigments in the shrimp and algae they eat. They can sleep standing on one leg without falling over.',
    'Lives in: lagoons in Africa and South America',
  ),
  item(
    'chameleon',
    'animals',
    'Chameleon',
    'uncommon',
    '🦎',
    'Chameleons change colour mostly to show their mood or talk to other chameleons, not just to hide. Each eye can look in a different direction at the same time.',
    'Lives in: forests in Madagascar and Africa',
    'Say: kuh-MEEL-yun',
  ),
  item(
    'sloth',
    'animals',
    'Sloth',
    'uncommon',
    '🦥',
    'Sloths move so slowly that algae grows on their fur, helping them blend into the trees. They only come all the way down to the ground about once a week.',
    'Lives in: rainforest trees in Central and South America',
  ),
  item(
    'octopus',
    'animals',
    'Octopus',
    'uncommon',
    '🐙',
    'An octopus has three hearts and can squeeze its whole soft body through a gap the size of its eye. It can also change colour in an instant to hide.',
    'Lives in: oceans worldwide',
  ),
  item(
    'seahorse',
    'animals',
    'Seahorse',
    'uncommon',
    '🐠',
    'Seahorses are one of the only animals where the father carries the babies, in a pouch on his belly. Many pairs stay loyal to each other through a whole breeding season.',
    'Lives in: seagrass meadows and coral reefs',
  ),
  item(
    'elephant',
    'animals',
    'Elephant',
    'common',
    '🐘',
    'Elephants use their trunks, which have no bones at all, for smelling, breathing, drinking, and gentle hugs. They are one of the few animals that can recognise themselves in a mirror.',
    'Lives in: savannas and forests in Africa and Asia',
  ),
  item(
    'giraffe',
    'animals',
    'Giraffe',
    'uncommon',
    '🦒',
    "A giraffe's tongue can be up to 45 cm long, perfect for reaching leaves high in the trees. They only need a few short hours of sleep a day.",
    'Lives in: savannas in Africa',
  ),
  item(
    'lion',
    'animals',
    'Lion',
    'common',
    '🦁',
    "A lion's roar can be heard up to 8 km away. Most of the hunting in a pride is done by the lionesses, working together as a team.",
    'Lives in: grasslands in Africa',
  ),
  item(
    'tiger',
    'animals',
    'Tiger',
    'uncommon',
    '🐯',
    'Every tiger has a one-of-a-kind stripe pattern, just like a human fingerprint. Their night vision is roughly six times better than ours.',
    'Lives in: forests in Asia',
  ),
  item(
    'polar-bear',
    'animals',
    'Polar bear',
    'uncommon',
    '🐻‍❄️',
    'Polar bears have black skin under fur that looks white but is actually see-through. Their fur and a thick layer of fat keep them warm in freezing water.',
    'Lives in: Arctic sea ice',
  ),
  item(
    'orca',
    'animals',
    'Orca',
    'uncommon',
    '🐋',
    'Orcas are actually the largest kind of dolphin, even though people often call them killer whales. Each pod has its own special set of calls, almost like a family language.',
    'Lives in: oceans worldwide',
  ),
  item(
    'hummingbird',
    'animals',
    'Hummingbird',
    'uncommon',
    '🐦',
    'Hummingbirds can beat their wings up to 80 times a second, letting them hover and even fly backwards. They must eat often, since hovering uses energy incredibly fast.',
    'Lives in: gardens and forests in the Americas',
  ),
  item(
    'red-panda',
    'animals',
    'Red panda',
    'rare',
    '🐾',
    'Red pandas have a false thumb, an extra wrist bone, to help them grip bamboo shoots. Their long bushy tail helps them balance while climbing trees.',
    'Lives in: mountain forests in China and Nepal',
  ),
  item(
    'poison-dart-frog',
    'animals',
    'Poison dart frog',
    'rare',
    '🐸',
    "A poison dart frog's bright colours warn other animals not to eat it. Frogs raised away from their wild rainforest diet are not poisonous at all.",
    'Lives in: rainforests in Central and South America',
  ),
  item(
    'snow-leopard',
    'animals',
    'Snow leopard',
    'rare',
    '🐆',
    'Snow leopards have huge paws that work like snowshoes on deep snow. Their thick tail can be almost as long as their body and wraps around them like a scarf.',
    'Lives in: mountains in Central Asia',
  ),
  item(
    'axolotl',
    'animals',
    'Axolotl',
    'rare',
    '🦎',
    'An axolotl can regrow a lost leg, tail, or even part of its heart. It usually keeps its gilled, tadpole-like look its whole life instead of growing up like other salamanders.',
    'Lives in: lakes near Mexico City',
    'Say: AK-suh-lot-ul',
  ),
  item(
    'pangolin',
    'animals',
    'Pangolin',
    'rare',
    '🐾',
    'A pangolin is covered in tough scales made of the same material as human fingernails. When frightened, it curls up into an armoured ball.',
    'Lives in: forests and grasslands in Africa and Asia',
    'Say: PAN-goh-lin',
  ),
  item(
    'giant-panda',
    'animals',
    'Giant panda',
    'rare',
    '🐼',
    'Giant pandas eat bamboo for up to 12 hours a day and can eat over 12 kg of it. A newborn panda cub is smaller than a stick of butter.',
    'Lives in: bamboo forests in China',
  ),
  item(
    'kakapo',
    'animals',
    'Kakapo',
    'epic',
    '🦜',
    'A kakapo is a large, flightless parrot from New Zealand that smells a bit like honey. It can live for 90 years, one of the longest-lived birds known.',
    'Lives in: forests on islands in New Zealand',
    'Say: KAH-kah-poh',
  ),
  item(
    'okapi',
    'animals',
    'Okapi',
    'epic',
    '🦓',
    'The okapi looks like a mix of a zebra and a giraffe, and it is actually a close cousin of the giraffe. It stayed unknown to scientists outside Africa until the early 1900s.',
    'Lives in: rainforests in Central Africa',
    'Say: oh-KAH-pee',
  ),
  item(
    'narwhal',
    'animals',
    'Narwhal',
    'epic',
    '🐳',
    "A narwhal's long spiral tusk is actually an overgrown tooth, mostly found on males. Scientists think it may help them sense changes in the water around them.",
    'Lives in: Arctic ocean waters',
    'Say: NAR-wal',
  ),
  item(
    'blue-whale',
    'animals',
    'Blue whale',
    'legendary',
    '🐋',
    'The blue whale is the largest animal ever known to have lived, even bigger than any dinosaur. Its heart alone can weigh as much as a small car.',
    'Lives in: oceans worldwide',
  ),

  // --- Space (16) -----------------------------------------------------------
  item(
    'moon',
    'space',
    'Moon',
    'common',
    '🌙',
    "The Moon is Earth's only natural satellite and the closest object in space to us. Its gravity pulls on the oceans and creates our tides.",
    'Orbits: Earth',
  ),
  item(
    'mars',
    'space',
    'Mars',
    'common',
    '🔴',
    'Mars is called the Red Planet because iron minerals on its surface have rusted. It is home to the tallest volcano in the solar system, Olympus Mons.',
    'Orbits: the Sun, 4th planet',
  ),
  item(
    'earth',
    'space',
    'Earth',
    'common',
    '🌍',
    'Earth is the only planet we know of with liquid water on its surface and life. From space, it looks like a blue marble because oceans cover most of it.',
    'Orbits: the Sun, 3rd planet',
  ),
  item(
    'sun',
    'space',
    'Sun',
    'common',
    '☀️',
    'The Sun is a giant ball of glowing gas that gives Earth its light and warmth. It is so big that about 1.3 million Earths could fit inside it.',
    'Located: centre of our solar system',
  ),
  item(
    'venus',
    'space',
    'Venus',
    'common',
    '🟡',
    'Venus is the hottest planet, even hotter than Mercury, because thick clouds trap heat like a blanket. A single day on Venus lasts longer than its whole year.',
    'Orbits: the Sun, 2nd planet',
  ),
  item(
    'jupiter',
    'space',
    'Jupiter',
    'common',
    '🟠',
    'Jupiter is the biggest planet in the solar system, so huge that all the other planets could fit inside it. Its Great Red Spot is a giant storm bigger than Earth.',
    'Orbits: the Sun, 5th planet',
  ),
  item(
    'mercury',
    'space',
    'Mercury',
    'uncommon',
    '⚪',
    'Mercury is the smallest planet and the closest to the Sun, zooming all the way around it in just 88 days. It has almost no atmosphere, so its temperature swings wildly.',
    'Orbits: the Sun, 1st planet',
  ),
  item(
    'saturn',
    'space',
    'Saturn',
    'uncommon',
    '🪐',
    "Saturn's beautiful rings are made mostly of chunks of ice and rock, some tiny and some as big as a house. It has more than 140 known moons.",
    'Orbits: the Sun, 6th planet',
  ),
  item(
    'neptune',
    'space',
    'Neptune',
    'uncommon',
    '🔵',
    'Neptune is the windiest planet, with storms racing faster than the speed of sound. It is so far from the Sun that its year lasts 165 Earth years.',
    'Orbits: the Sun, 8th planet',
  ),
  item(
    'uranus',
    'space',
    'Uranus',
    'uncommon',
    '🔵',
    'Uranus spins almost on its side, so it rolls around the Sun like a tipped-over ball. It looks pale blue because of methane gas in its atmosphere.',
    'Orbits: the Sun, 7th planet',
  ),
  item(
    'pluto',
    'space',
    'Pluto',
    'uncommon',
    '⚪',
    'Pluto is a dwarf planet in the icy Kuiper Belt, far beyond Neptune. It has a huge heart-shaped patch of frozen nitrogen that shows up clearly in photos.',
    'Orbits: the Sun, a dwarf planet',
  ),
  item(
    'comet',
    'space',
    'Comet',
    'rare',
    '☄️',
    'A comet is a ball of ice, dust, and rock that grows a glowing tail when it flies close to the Sun. Some comets take thousands of years to complete one loop.',
    'Orbits: the Sun in a long loop',
  ),
  item(
    'orion-nebula',
    'space',
    'Orion Nebula',
    'rare',
    '🌌',
    'The Orion Nebula is a giant cloud of gas and dust where new stars are being born right now. You can spot it with just your eyes, below the three stars of Orion’s belt.',
    'Located: the constellation Orion',
    'Say: oh-RY-un',
  ),
  item(
    'milky-way',
    'space',
    'Milky Way',
    'rare',
    '🌌',
    'The Milky Way is our home galaxy, home to our Sun and hundreds of billions of other stars. On a clear dark night, you can see it as a hazy band across the sky.',
    'Located: our home galaxy',
  ),
  item(
    'europa',
    'space',
    'Europa',
    'epic',
    '🌕',
    "Europa is one of Jupiter's moons, and it hides a deep ocean of liquid water under its icy shell. Scientists think it could be one of the best places to search for life beyond Earth.",
    'Orbits: Jupiter',
  ),
  item(
    'andromeda-galaxy',
    'space',
    'Andromeda galaxy',
    'legendary',
    '🌌',
    'The Andromeda galaxy is our nearest large galactic neighbour, so far away its light takes 2.5 million years to reach us. It contains roughly a trillion stars.',
    'Located: 2.5 million light-years away',
    'Say: an-DROM-eh-duh',
  ),
]

export function findItem(id: string): CollectionItem | undefined {
  return COLLECTION.find((c) => c.id === id)
}

export function itemsInSet(set: CollectionSet): CollectionItem[] {
  return COLLECTION.filter((c) => c.set === set)
}

export function itemImageUrl(item: CollectionItem): string {
  return `${import.meta.env.BASE_URL}collection/${item.id}.jpg`
}

export const RARITY_META: Record<Rarity, { label: string; stars: number; colour: string }> = {
  common: { label: 'Common', stars: 1, colour: '#9ca3af' },
  uncommon: { label: 'Uncommon', stars: 2, colour: '#22c55e' },
  rare: { label: 'Rare', stars: 3, colour: '#3b82f6' },
  epic: { label: 'Epic', stars: 4, colour: '#a855f7' },
  legendary: { label: 'Legendary', stars: 5, colour: '#f5b301' },
}
