// Built-in reading-passage library for Read Aloud. Pure TypeScript, no React.
import { wordCount } from './textSplit'

export type PassageLevel = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8

export type PassageSource = 'builtin' | 'typed' | 'photo' | 'book-excerpt' | 'book-original'

export interface ReadingPassage {
  id: string
  level: PassageLevel
  title: string
  text: string
  emoji: string
  wordCount: number
  focus: string
  source?: PassageSource
  sourceNote?: string
  addedAt?: number
}

/** Tiny fixed sight-word list allowed at every level. */
export const SIGHT_WORDS: readonly string[] = [
  'the',
  'a',
  'is',
  'i',
  'to',
  'and',
  'on',
  'in',
  'it',
  'has',
  'can',
  'see',
]

export const LEVELS: readonly { level: PassageLevel; name: string; focus: string; hint: string }[] = [
  { level: 1, name: 'Cat and hat', focus: 'short a', hint: 'Tiny short-a words like cat, hat, and nap.' },
  { level: 2, name: 'Pig and mud', focus: 'all short vowels', hint: 'Short a, e, i, o, u words like pig, bed, and hop.' },
  { level: 3, name: 'Fish and chips', focus: 'sh / ch / th / ck', hint: 'Digraphs like sh, ch, th, and ck.' },
  { level: 4, name: 'Frog and truck', focus: 'blends', hint: 'Blends like fl, st, gr, and nd.' },
  { level: 5, name: 'Cake and bike', focus: 'silent e', hint: 'Silent-e words like cake, ride, and hope.' },
  { level: 6, name: 'Tree and rain', focus: 'vowel teams', hint: 'Vowel teams like ee, ea, ai, ay, oa, and oo.' },
  { level: 7, name: 'Car and bird', focus: 'r-controlled', hint: 'Words like car, bird, and turn.' },
  { level: 8, name: 'Big stories', focus: 'sight words', hint: 'Longer sentences with lots of sight words.' },
]

/** Extra common sight words unlocked at level 8, on top of the lower levels. */
export const SIGHT_WORDS_L8: readonly string[] = [
  'said',
  'was',
  'were',
  'they',
  'there',
  'where',
  'what',
  'when',
  'who',
  'you',
  'your',
  'come',
  'some',
  'one',
  'two',
  'do',
  'does',
  'go',
  'goes',
  'of',
  'for',
  'from',
  'have',
  'here',
  'like',
  'little',
  'look',
  'my',
  'me',
  'we',
  'be',
  'he',
  'she',
  'no',
  'so',
  'are',
  'all',
  'with',
  'this',
  'that',
  'then',
  'them',
  'want',
  'went',
  'put',
  'play',
  'day',
  'away',
  'good',
  'very',
  'out',
  'our',
  'down',
  'up',
  'get',
  'make',
  'new',
  'now',
  'old',
]

/** Decodable words used by each level's built-in passages, plus a small buffer of extra common words. */
export const LEVEL_WORDS: Record<PassageLevel, readonly string[]> = {
  1: [
    'cat',
    'cats',
    'sat',
    'sad',
    'mad',
    'bad',
    'dad',
    'lad',
    'hat',
    'hats',
    'map',
    'maps',
    'jam',
    'ham',
    'hand',
    'hands',
    'sand',
    'cap',
    'caps',
    'man',
    'van',
    'fan',
    'pan',
    'ran',
    'tan',
    'rag',
    'bag',
    'bags',
    'wag',
    'tag',
    'gap',
    'lap',
    'nap',
    'naps',
    'tap',
    'taps',
    'yam',
    'cab',
    'ant',
    'ants',
    'at',
    'fat',
    'mat',
    'pat',
    'rat',
    'sam',
    'pam',
    'dan',
    'sap',
    'zap',
    'gas',
  ],
  2: [
    'pig',
    'pigs',
    'mud',
    'bed',
    'beds',
    'hop',
    'hops',
    'bug',
    'bugs',
    'nest',
    'nests',
    'hen',
    'hens',
    'pen',
    'pens',
    'ten',
    'wet',
    'red',
    'net',
    'nets',
    'fed',
    'leg',
    'legs',
    'hip',
    'hips',
    'kid',
    'kids',
    'wig',
    'wigs',
    'lid',
    'lids',
    'dig',
    'digs',
    'hit',
    'hits',
    'fin',
    'fins',
    'tin',
    'six',
    'mix',
    'fix',
    'pit',
    'sit',
    'sits',
    'big',
    'hog',
    'hogs',
    'dot',
    'dots',
    'pot',
    'pots',
    'top',
    'tops',
    'mop',
    'mops',
    'box',
    'boxes',
    'fox',
    'foxes',
    'cut',
    'but',
    'bun',
    'buns',
    'sun',
    'suns',
    'fun',
    'run',
    'runs',
    'hug',
    'hugs',
    'hum',
    'hut',
    'huts',
    'tub',
    'tubs',
    'cup',
    'cups',
    'pup',
    'pups',
    'mug',
    'mugs',
    'jug',
    'jugs',
    'rug',
    'rugs',
    'bud',
    'buds',
    'nut',
    'nuts',
    'gum',
    'up',
    'log',
    'logs',
    'hot',
    'tom',
    'ben',
    'lot',
    'gets',
    'get',
    'will',
    'dog',
    'dogs',
    'his',
    'got',
    'not',
    'rest',
  ],
  3: [
    'fish',
    'dish',
    'wish',
    'dash',
    'duck',
    'ducks',
    'rock',
    'rocks',
    'sock',
    'socks',
    'kick',
    'kicks',
    'chop',
    'chops',
    'bath',
    'this',
    'chip',
    'chips',
    'thin',
    'that',
    'thick',
    'chat',
    'chick',
    'chicks',
    'when',
    'such',
    'path',
    'paths',
    'shop',
    'shops',
    'ship',
    'ships',
    'then',
    'shed',
    'cash',
    'chin',
    'much',
    'rich',
    'luck',
    'lock',
    'locks',
    'pack',
    'pick',
    'sick',
    'buck',
    'tick',
    'wham',
    'whiz',
    'math',
    'with',
    'them',
    'shell',
    'shells',
  ],
  4: [
    'frog',
    'frogs',
    'jump',
    'jumps',
    'pond',
    'ponds',
    'glad',
    'stop',
    'stops',
    'stand',
    'spin',
    'spins',
    'skip',
    'skips',
    'fast',
    'small',
    'plant',
    'plants',
    'help',
    'helps',
    'mom',
    'truck',
    'trucks',
    'skid',
    'snack',
    'snacks',
    'snap',
    'clap',
    'claps',
    'camp',
    'tent',
    'tents',
    'black',
    'soft',
    'drop',
    'drum',
    'drums',
    'bang',
    'grab',
    'flag',
    'flap',
    'flat',
    'flip',
    'flop',
    'from',
    'grin',
    'grip',
    'step',
    'stamp',
    'spot',
    'slap',
    'slip',
    'sled',
    'swim',
    'swims',
    'twin',
    'drip',
    'plan',
    'block',
    'clip',
    'clock',
    'trap',
    'trip',
    'trips',
    'trick',
    'tricks',
    'crab',
    'band',
    'land',
    'wind',
    'hunt',
    'list',
    'last',
    'must',
    'best',
    'gift',
    'milk',
    'self',
    'melt',
  ],
  5: [
    'bake',
    'bakes',
    'cake',
    'cakes',
    'likes',
    'like',
    'nice',
    'taste',
    'ride',
    'rides',
    'bike',
    'bikes',
    'home',
    'use',
    'rope',
    'ropes',
    'game',
    'games',
    'make',
    'makes',
    'note',
    'notes',
    'mom',
    'five',
    'mice',
    'mouse',
    'same',
    'hole',
    'holes',
    'hide',
    'cute',
    'joke',
    'jokes',
    'tell',
    'tells',
    'smile',
    'smiles',
    'wave',
    'waves',
    'gave',
    'save',
    'cave',
    'name',
    'names',
    'came',
    'tape',
    'gate',
    'gates',
    'late',
    'date',
    'plate',
    'plates',
    'race',
    'face',
    'side',
    'wide',
    'time',
    'lime',
    'dive',
    'life',
    'hope',
    'nose',
    'rose',
    'bone',
    'cone',
    'stone',
    'stove',
    'poke',
    'smoke',
    'close',
    'cube',
    'tune',
    'huge',
  ],
  6: [
    'tree',
    'trees',
    'green',
    'bee',
    'bees',
    'seed',
    'seeds',
    'sits',
    'snail',
    'snails',
    'trail',
    'waits',
    'wait',
    'rain',
    'not',
    'kay',
    'day',
    'days',
    'play',
    'plays',
    'stay',
    'goat',
    'goats',
    'boat',
    'boats',
    'road',
    'roads',
    'float',
    'floats',
    'snow',
    'deep',
    'white',
    'melt',
    'cool',
    'pool',
    'pools',
    'swim',
    'swims',
    'tea',
    'leaf',
    'leaves',
    'sees',
    'neat',
    'team',
    'teams',
    'dream',
    'dreams',
    'win',
    'wins',
    'feet',
    'sheep',
    'sleep',
    'keep',
    'week',
    'weeks',
    'need',
    'needs',
    'feel',
    'meet',
    'sweet',
    'three',
    'teeth',
    'eat',
    'eats',
    'read',
    'reads',
    'seat',
    'beat',
    'clean',
    'sea',
    'main',
    'pain',
    'mail',
    'sail',
    'tail',
    'train',
    'trains',
    'paint',
    'say',
    'way',
    'may',
    'gray',
    'tray',
    'coat',
    'toad',
    'soap',
    'throw',
    'slow',
    'grow',
    'show',
    'low',
    'blow',
    'glow',
    'know',
    'moon',
    'soon',
    'food',
    'room',
    'spoon',
    'broom',
    'boot',
    'too',
    'zoo',
  ],
  7: [
    'farm',
    'farms',
    'barn',
    'barns',
    'dark',
    'hard',
    'park',
    'parks',
    'car',
    'cars',
    'cart',
    'carts',
    'star',
    'stars',
    'when',
    'bird',
    'birds',
    'yard',
    'yards',
    'chirp',
    'chirps',
    'dirt',
    'digs',
    'rest',
    'corn',
    'sort',
    'short',
    'turn',
    'turns',
    'trip',
    'trips',
    'girl',
    'girls',
    'fern',
    'ferns',
    'her',
    'best',
    'surf',
    'surfs',
    'did',
    'get',
    'hurt',
    'first',
    'claps',
    'clap',
    'for',
    'sits',
    'win',
    'zip',
    'zips',
    'far',
    'shark',
    'sharks',
    'art',
    'harm',
    'arm',
    'arms',
    'jar',
    'jars',
    'chart',
    'born',
    'fort',
    'sport',
    'storm',
    'form',
    'worn',
    'torn',
    'herd',
    'germ',
    'term',
    'shirt',
    'shirts',
    'firm',
    'third',
    'fur',
    'burn',
    'curl',
    'nurse',
    'purse',
  ],
  8: [
    'dog',
    'dogs',
    'his',
    'got',
    'book',
    'books',
    'at',
    'bed',
    'took',
    'looks',
    'wants',
    'friend',
    'friends',
  ],
}

function passage(
  id: string,
  level: PassageLevel,
  title: string,
  emoji: string,
  text: string,
  focus: string,
): ReadingPassage {
  return {
    id,
    level,
    title,
    text,
    emoji,
    wordCount: wordCount(text),
    focus,
    source: 'builtin',
  }
}

const L1_FOCUS = 'short a'
const L2_FOCUS = 'all short vowels'
const L3_FOCUS = 'sh / ch / th / ck'
const L4_FOCUS = 'blends'
const L5_FOCUS = 'silent e'
const L6_FOCUS = 'vowel teams'
const L7_FOCUS = 'r-controlled'
const L8_FOCUS = 'sight words'

export const PASSAGES: readonly ReadingPassage[] = [
  // Level 1 - short a
  passage('l1-cat-nap', 1, 'Cat Nap', '🐱', 'The cat sat. The cat has a nap.', L1_FOCUS),
  passage('l1-fat-cat', 1, 'Fat Cat', '🐈', 'A fat cat can nap. It has a mat.', L1_FOCUS),
  passage('l1-sad-lad', 1, 'Sad Lad', '😢', 'The lad is sad. Dad has a bad hat.', L1_FOCUS),
  passage('l1-tan-van', 1, 'Tan Van', '🚐', 'The van is tan. Sam ran to the van.', L1_FOCUS),
  passage('l1-pat-the-cat', 1, 'Pat the Cat', '🐾', 'Pam can pat the cat. The cat is mad.', L1_FOCUS),
  passage('l1-map-nap', 1, 'Map Nap', '🗺️', 'Dan has a map. Dan can nap on it.', L1_FOCUS),
  passage('l1-bag-of-jam', 1, 'Bag of Jam', '🍯', 'Sam has a bag. The bag has jam.', L1_FOCUS),
  passage('l1-tap-tap', 1, 'Tap Tap', '👏', 'Cat can tap. Cat can tap the mat.', L1_FOCUS),

  // Level 2 - all short vowels
  passage('l2-pig-in-mud', 2, 'Pig in Mud', '🐷', 'The pig sat in mud. The pig is wet.', L2_FOCUS),
  passage('l2-ten-hens', 2, 'Ten Hens', '🐔', 'Ten hens sit on a log. The hens can nap.', L2_FOCUS),
  passage('l2-bug-on-a-rug', 2, 'Bug on a Rug', '🐛', 'A bug is on the rug. The bug can hop.', L2_FOCUS),
  passage('l2-fox-in-a-box', 2, 'Fox in a Box', '🦊', 'A fox sat in a box. The fox can hop and run.', L2_FOCUS),
  passage('l2-sun-and-fun', 2, 'Sun and Fun', '☀️', 'The sun is hot. Ten kids run in the sun.', L2_FOCUS),
  passage('l2-wig-and-pup', 2, 'Wig and Pup', '🐶', 'The pup has a wig. The pup can dig.', L2_FOCUS),
  passage('l2-top-and-mop', 2, 'Top and Mop', '🧹', 'Tom has a top. Tom can mop up the mud.', L2_FOCUS),
  passage('l2-nuts-in-a-cup', 2, 'Nuts in a Cup', '🥜', 'Ben has nuts in a cup. Ben can hum and run.', L2_FOCUS),

  // Level 3 - digraphs
  passage(
    'l3-fish-wish',
    3,
    'Fish Wish',
    '🐟',
    'The fish is in the dish. It has a big wish. The fish can dash.',
    L3_FOCUS,
  ),
  passage(
    'l3-duck-on-a-rock',
    3,
    'Duck on a Rock',
    '🦆',
    'A duck sat on a rock. The duck can kick a sock. Then the duck ran.',
    L3_FOCUS,
  ),
  passage(
    'l3-chop-chop',
    3,
    'Chop Chop',
    '🔪',
    'Dad can chop. Dad can chop a lot. Then Dad can nap.',
    L3_FOCUS,
  ),
  passage(
    'l3-bath-time',
    3,
    'Bath Fun',
    '🛁',
    'The pup gets a bath. The pup is wet. This is fun.',
    L3_FOCUS,
  ),
  passage(
    'l3-thin-chip',
    3,
    'Thin Chip',
    '🍪',
    'This chip is thin. That chip is thick. Dad has a chip.',
    L3_FOCUS,
  ),
  passage(
    'l3-chat-chat',
    3,
    'Chat Chat',
    '🐔',
    'The hen and chick chat. The hen has a chick. When can the chick nap?',
    L3_FOCUS,
  ),
  passage(
    'l3-sock-puppet',
    3,
    'Sock Puppet',
    '🧦',
    'Dad has a sock. The sock can chat. This sock is such fun.',
    L3_FOCUS,
  ),
  passage(
    'l3-path-to-shop',
    3,
    'Path to Shop',
    '🏪',
    'Dad and the pup hop on a path. Then Dad can shop. This is fun.',
    L3_FOCUS,
  ),

  // Level 4 - blends
  passage(
    'l4-frog-on-a-log',
    4,
    'Frog on a Log',
    '🐸',
    'A frog can hop on a log. The frog can jump in the pond. The frog is glad.',
    L4_FOCUS,
  ),
  passage(
    'l4-stop-and-stand',
    4,
    'Stop and Stand',
    '🛑',
    'Dad can stop and stand. Dad can spin and skip. This is fast fun.',
    L4_FOCUS,
  ),
  passage(
    'l4-plant-a-plant',
    4,
    'Plant a Plant',
    '🌱',
    'Mom can plant a plant. The plant is small. Mom and Dad help the plant.',
    L4_FOCUS,
  ),
  passage(
    'l4-truck-trick',
    4,
    'Truck Trick',
    '🚚',
    'The truck is fast. The truck can stop and skid. This truck is a big hit.',
    L4_FOCUS,
  ),
  passage(
    'l4-snack-snap',
    4,
    'Snack Snap',
    '🍿',
    'Dad has a snack. Dad can snap and clap. This snack is a big hit.',
    L4_FOCUS,
  ),
  passage(
    'l4-camp-tent',
    4,
    'Camp Tent',
    '⛺',
    'Dad and the kids camp. The tent is big. The kids can nap in the tent.',
    L4_FOCUS,
  ),
  passage(
    'l4-black-cat-nap',
    4,
    'Black Cat Nap',
    '⚫',
    'The black cat can nap. The cat has a soft mat. The cat is glad.',
    L4_FOCUS,
  ),
  passage(
    'l4-drop-the-drum',
    4,
    'Drop the Drum',
    '🥁',
    'Ben can bang the drum. Ben can drop the drum. Then Ben can grab the drum.',
    L4_FOCUS,
  ),

  // Level 5 - silent e
  passage(
    'l5-bake-a-cake',
    5,
    'Bake a Cake',
    '🎂',
    'Mom can bake a cake. Dad likes the cake a lot. The cake has a nice taste.',
    L5_FOCUS,
  ),
  passage(
    'l5-bike-ride',
    5,
    'Bike Ride',
    '🚲',
    'Sam can ride a bike. The bike is fast and fun. Sam likes to ride the bike.',
    L5_FOCUS,
  ),
  passage(
    'l5-home-time',
    5,
    'Home Time',
    '🏠',
    'Dad and Sam sit at home. The home is nice. Sam and Dad rest at home.',
    L5_FOCUS,
  ),
  passage(
    'l5-rope-game',
    5,
    'Rope Game',
    '🪢',
    'Sam has a rope. Sam and Dad use the rope. This rope game is such fun.',
    L5_FOCUS,
  ),
  passage(
    'l5-nice-note',
    5,
    'Nice Note',
    '📝',
    'Sam can make a note. The note is to Mom. Mom likes the nice note.',
    L5_FOCUS,
  ),
  passage(
    'l5-five-mice',
    5,
    'Five Mice',
    '🐭',
    'Dad can see five mice. The mice like the same hole. The mice hide and nap.',
    L5_FOCUS,
  ),
  passage(
    'l5-cute-pup',
    5,
    'Cute Pup',
    '🐶',
    'Sam has a cute pup. The pup likes to run and jump. The pup is glad it is home.',
    L5_FOCUS,
  ),
  passage(
    'l5-dads-joke',
    5,
    'Dad Tells a Joke',
    '😄',
    'Dad can tell a joke. The joke makes Sam smile. Sam likes jokes a lot.',
    L5_FOCUS,
  ),

  // Level 6 - vowel teams
  passage(
    'l6-green-tree',
    6,
    'Green Tree',
    '🌳',
    'The tree is green. Sam can see a bee in the tree. The bee sits on the seed.',
    L6_FOCUS,
  ),
  passage(
    'l6-rain-and-snail',
    6,
    'Rain and Snail',
    '🐌',
    'The rain can drop. A snail sits on the trail. The snail is not sad in the rain.',
    L6_FOCUS,
  ),
  passage(
    'l6-day-to-play',
    6,
    'Day to Play',
    '🏖️',
    'The day is nice and fun. Sam and Kay play in the rain. Sam and Kay stay to play.',
    L6_FOCUS,
  ),
  passage(
    'l6-goat-on-a-boat',
    6,
    'Goat on a Boat',
    '🐐',
    'A goat sits on a boat. The boat is on the road. The goat is glad it can float.',
    L6_FOCUS,
  ),
  passage(
    'l6-snow-day',
    6,
    'Snow Day',
    '❄️',
    'The snow is deep and white. Sam and Dad play in the snow. The snow will not melt fast.',
    L6_FOCUS,
  ),
  passage(
    'l6-cool-pool-day',
    6,
    'Cool Pool Day',
    '🏊',
    'Sam and Dad swim fast in the cool pool. The pool is deep. Sam can float and swim.',
    L6_FOCUS,
  ),
  passage(
    'l6-tea-and-leaf',
    6,
    'Tea and Leaf',
    '🍵',
    'Sam has a cup and tea. Sam sees a leaf on the tea. The leaf is green and neat.',
    L6_FOCUS,
  ),
  passage(
    'l6-team-dream',
    6,
    'Team Dream',
    '⚽',
    'Sam is on a fun team. The team has a big dream. The team can win a lot.',
    L6_FOCUS,
  ),

  // Level 7 - r-controlled
  passage(
    'l7-farm-and-barn',
    7,
    'Farm and Barn',
    '🚜',
    'The farm has a big barn. A goat and a hen sit on the farm. The barn is dark and hard to see.',
    L7_FOCUS,
  ),
  passage(
    'l7-park-day',
    7,
    'Park Day',
    '🌳',
    'Sam and Dad park the car. Sam can run in the park. The park has a big cart. Sam sees a star when it is dark.',
    L7_FOCUS,
  ),
  passage(
    'l7-bird-in-yard',
    7,
    'Bird in Yard',
    '🐦',
    'A bird sits in the yard. The bird can chirp. The bird digs in the dirt. Then the bird can rest.',
    L7_FOCUS,
  ),
  passage(
    'l7-corn-farm',
    7,
    'Corn Farm',
    '🌽',
    'Dad has corn on the farm. The corn is in the barn. Sam and Dad sort the corn. This corn is fun to eat.',
    L7_FOCUS,
  ),
  passage(
    'l7-short-trip',
    7,
    'Short Trip',
    '🚗',
    'Sam and Dad ride in the car. It is a short trip. The car can turn and zip fast. Sam has fun on the trip.',
    L7_FOCUS,
  ),
  passage(
    'l7-girl-and-fern',
    7,
    'Girl and Fern',
    '🌿',
    'A girl has a fern. The girl can help the fern. The fern is her best plant. The girl is glad.',
    L7_FOCUS,
  ),
  passage(
    'l7-fun-in-the-surf',
    7,
    'Fun in the Surf',
    '🏄',
    'Sam and Dad can surf. Sam can turn in the surf. The surf is fun. Sam did not get hurt.',
    L7_FOCUS,
  ),
  passage(
    'l7-first-in-yard',
    7,
    'First in Yard',
    '🥇',
    'Sam is first in the yard. Sam can jump and turn. Sam is glad Sam is first. Dad claps for Sam.',
    L7_FOCUS,
  ),

  // Level 8 - sight words
  passage(
    'l8-day-at-the-park',
    8,
    'A Day at the Park',
    '🌳',
    'Sam and Kay went to the park. They see a little dog and a big frog. Sam said the frog can jump far. Kay is very glad they come to play.',
    L8_FOCUS,
  ),
  passage(
    'l8-new-pup',
    8,
    'The New Pup',
    '🐕',
    'Sam has a new pup. The pup is little and cute. Sam and the pup go to the park. They play and run all day.',
    L8_FOCUS,
  ),
  passage(
    'l8-where-is-my-hat',
    8,
    'Where Is My Hat',
    '🎩',
    'Sam looks and looks for his hat. Where is the hat? Dad said it is on the bed. Sam is very glad to see it.',
    L8_FOCUS,
  ),
  passage(
    'l8-two-little-birds',
    8,
    'Two Little Birds',
    '🐦',
    'Sam sees two little birds. The birds sit on the farm. They do not go away. Sam likes to look at them and smile.',
    L8_FOCUS,
  ),
  passage(
    'l8-good-old-book',
    8,
    'Good Old Book',
    '📚',
    'Dad has a good old book. The book has a little cat in it. Sam likes to look at the book. Sam wants to read it too.',
    L8_FOCUS,
  ),
  passage(
    'l8-what-do-you-see',
    8,
    'What Do You See',
    '👀',
    'What do you see at the park? I see a big dog and a little cat. I see a red bird too. Do you like the park?',
    L8_FOCUS,
  ),
  passage(
    'l8-my-best-day',
    8,
    'My Best Day',
    '🌟',
    'This day was very good for me. Sam and Dad went to the park. Sam got a new book. Sam and Dad read the book at home.',
    L8_FOCUS,
  ),
  passage(
    'l8-she-and-he-play',
    8,
    'She and He Play',
    '👫',
    'She has a red hat. He has a little dog. She and he go to the park. They play and have fun with the dog.',
    L8_FOCUS,
  ),
]

/** One placeholder "My books" seed passage, used to exercise the book-lookup flows. */
export const SEED_BOOKS: readonly ReadingPassage[] = [
  {
    id: 'book-princess-in-black-science-fair',
    level: 3,
    title: 'The Princess in Black and the Science Fair Scare',
    text:
      'Magnolia is a princess who loves science. At the fair, a big blob of goo pops up and wiggles! ' +
      'Magnolia and her pony Blacky rush in to help. Soon the silly goo blob turns into a happy new friend.',
    emoji: '🦄',
    wordCount: wordCount(
      'Magnolia is a princess who loves science. At the fair, a big blob of goo pops up and wiggles! ' +
        'Magnolia and her pony Blacky rush in to help. Soon the silly goo blob turns into a happy new friend.',
    ),
    focus: 'sh / ch / th',
    source: 'book-original',
    sourceNote: "Made up from the story - not the book's words",
  },
]

export function passageById(
  id: string,
  extra?: readonly ReadingPassage[],
): ReadingPassage | undefined {
  const all: readonly ReadingPassage[] = extra ? [...PASSAGES, ...SEED_BOOKS, ...extra] : [...PASSAGES, ...SEED_BOOKS]
  return all.find((p) => p.id === id)
}

export function passagesForLevel(level: PassageLevel): ReadingPassage[] {
  return PASSAGES.filter((p) => p.level === level)
}

export function levelInfo(level: PassageLevel): { level: PassageLevel; name: string; focus: string; hint: string } | undefined {
  return LEVELS.find((l) => l.level === level)
}
